services:
  - type: web
    name: cyber-shield-linkguard
    env: python
    buildCommand: |
      apt-get update && apt-get install -y zbar-tools libzbar0
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --bind 0.0.0.0:$PORT
